# Header
menu:
  主页: /
  所有文章: /archives
  # 随笔: /tags/随笔

# SubNav
subnav:
  github: "https://github.com/wylyeak"
  weibo: "http://weibo.com/wylhelp"
  rss: "http://feed.feedsky.com/wylyeak"
  # facebook: "/"
  # google: "/"
  # twitter: "/"
  # linkedin: "/"

rss: /atom.xml

# Content
excerpt_link: more
fancybox: true

# Miscellaneous

favicon: /favicon.png

#你的头像
avatar: "https://avatars2.githubusercontent.com/u/1926058?v=2&s=460"
#是否开启分享
share: true
#是否开启多说评论，填写你在多说申请的项目名称
duoshuo: wylyeak
#是否开启云标签
tagcloud: true
